version: '3.3'

services:
  pbl2-zookeeper:
    image: bitnami/zookeeper:3.8
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mojadol-network

  pbl2-kafka1:
    image: bitnami/kafka:3.4
    container_name: pbl2-kafka1
    ports:
      - "29092:29092"
    environment:
        - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://pbl2-kafka1:29092
        - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
        - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
        - KAFKA_ZOOKEEPER_CONNECT=pbl2-zookeeper:2181 # Zookeeper의 호스트:포트 주소
        - KAFKA_BROKER_ID=1 # 브로커 고유 ID
        - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3 # Kafka 내부에서 사용하는 offset topic의 복제 계수
        - KAFKA_CFG_KRAFT_MODE=false
    networks:
      - mojadol-network
    depends_on:
      - pbl2-zookeeper

  pbl2-kafka2:
    image: bitnami/kafka:3.4
    container_name: pbl2-kafka2
    ports:
      - "29093:29093"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://pbl2-kafka2:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=pbl2-zookeeper:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_KRAFT_MODE=false
    networks:
      - mojadol-network
    depends_on:
      - pbl2-zookeeper

  pbl2-kafka3:
    image: bitnami/kafka:3.4
    container_name: pbl2-kafka3
    ports:
      - "29094:29094"
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://pbl2-kafka3:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_ZOOKEEPER_CONNECT=pbl2-zookeeper:2181
      - KAFKA_BROKER_ID=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=3
      - KAFKA_CFG_KRAFT_MODE=false
    networks:
      - mojadol-network
    depends_on:
      - pbl2-zookeeper

networks:
  mojadol-network:
    external: true
