version: '3.3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: pbl2-prometheus
    volumes:
      - /home/bgt/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - mojadol-network

  grafana:
    image: grafana/grafana:latest
    container_name: pbl2-grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL}
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - mojadol-network

volumes:
  grafana-storage:

networks:
  mojadol-network:
    external: true
