spring:
  #profiles:
    #active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL_PBL2}?serverTimezone=Asia/Seoul
    username: ${DB_USER_NAME_PBL2}
    password: ${DB_PASSWORD_PBL2}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true # true ??? JPA ??? ?? ??
      format-sql: true # JPA? ???? Hibernate? ????? ???? SQL? ???? ????.
      generate-ddl: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
    open-in-view: false # Lazy Loading 경고 API응답속도 최적화를 위해 false
  web:
    client:
      connection-timeout: 600000
      read-timeout: 600000
  data:
    redis:
      host: ${REDIS_HOST_PBL2}
      port: ${REDIS_PORT_PBL2}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_MAIL_USERNAME}
    password: ${MY_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  kafka:
    bootstrap-servers:
      - pbl2-kafka1:29092
      - pbl2-kafka2:29093
      - pbl2-kafka3:29094
    consumer:
      group-id: group1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


external:
  django:
    url: ${DJANGO_BASE_URL}

jwt:
  secret: ${JWT_TOKEN_PBL_2}
  access-token:
    expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  refresh-token:
    expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}

server:
  address: 0.0.0.0
  port: 4400

sftp:
  username: ${SSH_USERNAME_PBL2}
  port: ${SSH_PORT_PBL2}
  password: ${SSH_PASSWORD_PBL2}
  host: ${SSH_HOST_PBL2}


management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    enable:
      tomcat: true


logging:
  level:
    org.springframework: info
    org.hibernate: warn
    com.gnu.pbl2: info

