name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'dispatch'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        run: nc -zv ${{ secrets.SSH_HOST_PBL2 }} ${{ secrets.SSH_PORT_PBL2 }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Container Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-be:latest

      - name: Create .env file
        run: |
          mkdir -p /home/bgt/pbl2
          touch /home/bgt/pbl2/.env
          echo "DB_URL_PBL2=${{ secrets.DB_URL_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "DB_USER_NAME_PBL2=${{ secrets.DB_USER_NAME_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "DB_PASSWORD_PBL2=${{ secrets.DB_PASSWORD_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "REDIS_HOST_PBL2=${{ secrets.REDIS_HOST_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "REDIS_PORT_PBL2=${{ secrets.REDIS_PORT_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "SSH_USERNAME_PBL2=${{ secrets.SSH_USERNAME_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "SSH_PORT_PBL2=${{ secrets.SSH_PORT_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "SSH_PASSWORD_PBL2=${{ secrets.SSH_PASSWORD_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "SSH_HOST_PBL2=${{ secrets.SSH_HOST_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "JWT_TOKEN_PBL_2=${{ secrets.JWT_TOKEN_PBL_2 }}" >> /home/bgt/pbl2/.env
          echo "JWT_ACCESS_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }}" >> /home/bgt/pbl2/.env
          echo "JWT_REFRESH_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_TIME }}" >> /home/bgt/pbl2/.env
          echo "FIREBASE_PROJECT_ID_PBL2=${{ secrets.FIREBASE_PROJECT_ID_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "FIREBASE_PRIVATE_KEY_ID_PBL2=${{ secrets.FIREBASE_PRIVATE_KEY_ID_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "FIREBASE_PRIVATE_KEY_PBL2=${{ secrets.FIREBASE_PRIVATE_KEY_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "FIREBASE_CLIENT_EMAIL_PBL2=${{ secrets.FIREBASE_CLIENT_EMAIL_PBL2 }}" >> /home/bgt/pbl2/.env
          echo "FIREBASE_CLIENT_ID_PBL2=${{ secrets.FIREBASE_CLIENT_ID_PBL2 }}" >> /home/bgt/pbl2/.env


      - name: Debug .env file
        run: |
          ls -lah /home/bgt/pbl2/
          cat /home/bgt/pbl2/.env
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          timeout: 600s
          command_timeout: 600s
          debug: true
          script: |
            set -ex  # 에러 발생 시 즉시 종료 + 실행된 명령어 로그 출력
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker network create mojadol-network || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-be:latest
            docker rm -f pbl2-be || true
            docker rm -f mojadol-redis || true
            docker run -d \
              --name mojadol-redis \
              -p 4479:4479 \
              --network mojadol-network \
              --restart always \
              redis:latest \
              redis-server --appendonly yes --replica-read-only no
            docker run -d \
              --env-file /home/bgt/pbl2/.env \
              --restart=always \
              --name pbl2-be \
              --network mojadol-network \
              -p 4400:4400 \
              -v /home/bgt/pbl2:/home/bgt/pbl2 \
              ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-be:latest
