name: ci/cd pbl2

on:
  push:
    branches:
      - "main"

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      tags:
        description: 'dispatch'

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        run: nc -zv ${{ secrets.SSH_HOST_PBL2 }} ${{ secrets.SSH_PORT_PBL2 }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Container Image (Debian 기반으로 변경)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-be:latest

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PBL2 }}
          username: ${{ secrets.SSH_USERNAME_PBL2 }}
          password: ${{ secrets.SSH_PASSWORD_PBL2 }}
          port: ${{ secrets.SSH_PORT_PBL2 }}
          timeout: 600s
          command_timeout: 600s
          debug: true
          script: |
            set -ex  # 에러 발생 시 즉시 종료 + 실행된 명령어 로그 출력
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            docker network create mojadol-network || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pbl2-be:latest
            docker rm -f mojadol-be || true
            docker rm -f mojadol-redis || true
            docker run -d \
              --name mojadol-redis \
              -p 4479:4479 \
              --network mojadol-network \
              --restart always \
              redis:latest \
              mojadol-redis --appendonly yes --replica-read-only no
            docker run -d \
              --restart=always \
              --name pbl2-be \
              --network mojadol-network \
              -p 4400:4400 \
              -e DB_URL_PBL2=${{ secrets.DB_URL_PBL2 }} \
              -e DB_USER_NAME_PBL2=${{ secrets.DB_USER_NAME_PBL2 }} \
              -e DB_PASSWORD_PBL2=${{ secrets.DB_PASSWORD_PBL2 }} \
              -e REDIS_HOST_PBL2=${{ secrets.REDIS_HOST_PBL2 }} \
              -e REDIS_PORT_PBL2=${{ secrets.REDIS_PORT_PBL2 }} \
              -e SSH_USERNAME_PBL2=${{ secrets.SSH_USERNAME_PBL2 }} \
              -e SSH_PORT_PBL2=${{ secrets.SSH_PORT_PBL2 }} \
              -e SSH_PASSWORD_PBL2=${{ secrets.SSH_PASSWORD_PBL2 }} \
              -e SSH_HOST_PBL2=${{ secrets.SSH_HOST_PBL2 }} \
              -e JWT_TOKEN_PBL_2=${{ secrets.JWT_TOKEN_PBL_2 }} \
              -e JWT_ACCESS_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }} \
              -e JWT_REFRESH_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_REFRESH_TOKEN_EXPIRATION_TIME }} \
              -v /home/bgt/Gaechuck-Backend:/home/bgt/Gaechuck-Backend \
              ${{ secrets.DOCKERHUB_USERNAME }}/gaechuck-be:latest